import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "../../../lib/supabase/server";
import "./book.css";

const checkoutUrl = "/checkout/ego-and-empathy";
const coverUrl = "/books/ego-empathy-cover.svg";

export const metadata: Metadata = { title: "Ego & Empathy Book by Bharath Kumar Arekapudi", description: "Explore Ego & Empathy by Bharath Kumar Arekapudi, a practical book about self-awareness, relationships, leadership, and balancing personal drive with understanding others.", alternates:{canonical:"/books/ego-and-empathy"}, openGraph:{type:"book",title:"Ego & Empathy",description:"A practical exploration of balancing self-belief, awareness, and empathy.",url:"/books/ego-and-empathy",images:[{url:coverUrl,alt:"Ego & Empathy book cover"}]}};

export default async function EgoAndEmpathyBookPage() {
  const supabase = await createClient();
  const { data: book } = await supabase.from("books").select("slug,title,subtitle,description,cover_image_url,price_amount,shipping_amount,status").eq("slug","ego-and-empathy").maybeSingle();
  if (!book || book.status !== "active") notFound();
  const bookSchema = {"@context":"https://schema.org","@type":"Book",name:book.title,author:{"@type":"Person",name:"Bharath Kumar Arekapudi"},url:"https://www.shiftleftcc.com/books/ego-and-empathy",image:book.cover_image_url || coverUrl,offers:{"@type":"Offer",price:(book.price_amount/100).toFixed(2),priceCurrency:"USD",availability:"https://schema.org/InStock",url:"https://www.shiftleftcc.com/checkout/ego-and-empathy",shippingDetails:{"@type":"OfferShippingDetails",shippingRate:{"@type":"MonetaryAmount",value:(book.shipping_amount/100).toFixed(2),currency:"USD"},shippingDestination:{"@type":"DefinedRegion",addressCountry:"US"}}}};
  return <main className="bookPage"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(bookSchema)}}/><section className="bookHero"><div className="bookCoverWrap"><img src={book.cover_image_url || coverUrl} alt={`${book.title} by Bharath Kumar Arekapudi`} className="bookCover"/></div><div className="bookHeroCopy"><p className="eyebrow">A BOOK BY BHARATH KUMAR AREKAPUDI</p><h1>{book.title}</h1><p className="bookLead">{book.subtitle || "A practical exploration of how self-belief and empathy shape our choices, relationships, leadership, and personal growth."}</p><p>{book.description}</p><p><strong>${(book.price_amount/100).toFixed(2)}</strong> · Regular paperback · ${(book.shipping_amount/100).toFixed(2)} U.S. shipping</p><div className="bookActions"><Link className="button primary" href={checkoutUrl}>Buy Now</Link><Link className="button secondary" href="/books">All Books</Link></div><p className="purchaseNote">Secure direct checkout is handled through Stripe. Card details are never stored by Shift Left.</p></div></section><section className="bookContentSection"><div><p className="eyebrow">WHY THIS BOOK</p><h2>Build confidence without losing connection.</h2><p>Ego and empathy are often treated as opposites. In practice, both can serve an important purpose. The challenge is recognizing when confidence becomes defensiveness, when ambition overshadows relationships, or when empathy needs stronger boundaries.</p><p>This book brings those ideas into everyday life, helping readers reflect on how they communicate, make decisions, lead, respond to conflict, and understand the experiences of others.</p></div><div className="bookTakeaways"><article><span>01</span><h3>Understand ego</h3><p>Recognize how ego can support identity and confidence—and how it can also create blind spots.</p></article><article><span>02</span><h3>Strengthen empathy</h3><p>Listen more deeply, understand other perspectives, and create stronger relationships.</p></article><article><span>03</span><h3>Find balance</h3><p>Make thoughtful decisions that respect both your own needs and the needs of others.</p></article><article><span>04</span><h3>Lead intentionally</h3><p>Apply self-awareness, empathy, and accountability in leadership, family, work, and community.</p></article></div></section><section className="bookFinalCta"><p className="eyebrow">START READING</p><h2>Explore the balance between self-belief and understanding others.</h2><div className="bookActions centered"><Link className="button primary" href={checkoutUrl}>Buy Now — ${(book.price_amount/100).toFixed(2)}</Link></div></section></main>;
}
