import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "../../../lib/supabase/server";
import "../ego-and-empathy/book.css";

export default async function MindFitnessPage() {
  const supabase = await createClient();
  const { data: book } = await supabase.from("books").select("slug,title,subtitle,description,cover_image_url,price_amount,shipping_amount,status").eq("slug","mind-fitness").maybeSingle();
  if (!book || book.status !== "active") notFound();
  return <main className="bookPage"><section className="bookHero"><div className="bookCoverWrap"><img src={book.cover_image_url || "/books/mind-fitness-cover.svg"} alt={`${book.title} by Bharath Kumar Arekapudi`} className="bookCover" /></div><div className="bookHeroCopy"><p className="eyebrow">A BOOK BY BHARATH KUMAR AREKAPUDI</p><h1>{book.title}</h1>{book.subtitle && <p className="bookLead">{book.subtitle}</p>}<p>{book.description}</p><p><strong>${(book.price_amount/100).toFixed(2)}</strong> · Regular paperback · ${(book.shipping_amount/100).toFixed(2)} U.S. shipping</p><div className="bookActions"><Link className="button primary" href="/checkout/mind-fitness">Buy Now</Link><Link className="button secondary" href="/books">All Books</Link></div><p className="purchaseNote">Secure direct checkout is handled through Stripe. Card details are never stored by Shift Left.</p></div></section><section className="bookContentSection"><div><p className="eyebrow">WHY THIS BOOK</p><h2>Apply an IT mindset to mind fitness.</h2><p>Mind Fitness: Through IT Strategies uses familiar technology and IT ideas as practical metaphors for personal wellbeing. It invites readers to think about maintenance, monitoring, upgrades, resilience, inputs, and recovery as part of caring for the mind with the same intention used to care for important systems.</p></div><div className="bookTakeaways"><article><span>01</span><h3>Notice earlier</h3><p>Recognize signals before stress and overload become harder to manage.</p></article><article><span>02</span><h3>Build resilience</h3><p>Create routines and strategies that support recovery and sustainable performance.</p></article><article><span>03</span><h3>Use practical frameworks</h3><p>Translate familiar technology concepts into simple wellbeing actions.</p></article><article><span>04</span><h3>Keep upgrading</h3><p>Treat wellbeing as an ongoing practice rather than a one-time fix.</p></article></div></section></main>;
}
